### PR TITLE
Added the files for kata args, passed by lint and jest

### PR DESCRIPTION
**Pull request by MatiasVerdugo**

### CODE REVIEW

**Comment by J0c4** [comment]
I detect copy paste here, is this really your code? purpose of katas if for you to practice and keep improving your coding skills, if resolution is copied, that goal will not be achieved

**Comment by J0c4** [comment]
hi @MatiasVerdugo , any updates on this one? Since its been a while for this PR, we will need to set tomorrow as a deadline so we can close it

**Comment by MatiasVerdugo** [comment]
> hi @MatiasVerdugo , any updates on this one? Since its been a while for this PR, we will need to set tomorrow as a deadline so we can close it

There is no copy paste, but a friend who knows a lot about JS helped me, with almost all the code, I didn't know how to do it

**Comment by J0c4** [comment]
> > hi @MatiasVerdugo , any updates on this one? Since its been a while for this PR, we will need to set tomorrow as a deadline so we can close it
> 
> There is no copy paste, but a friend who knows a lot about JS helped me, with almost all the code, I didn't know how to do it

I mention the copy paste because the code you uploaded is basically the same in this repo: https://github.com/nealhu/args-kata/tree/master/javascript/before-refactor.

Unfortunately, we cannot merge since this code was not authored by you. As we have reached the deadline, we will have to close it without merging. Still, we can follow up any questions that you might have.

**Pull request closed without merging**
